### ISSUE TITLE
Create initial design and tests Q&A wiki page

### ISSUE THREAD

**Issue by JasonPuglisi** [JasonPuglisi/emmental#14]
### Acceptance Criteria

1. The attached documentation questions are answered in a wiki page

### Questions

1. What Web Application security mechanisms are involved in your topology? What security mechanisms would ideally be involved?
1. What testing framework did you choose and why?

**Comment by tanner-g** [comment]
I've added some questions for the group to look at about activity 2. Nevertheless, I think it is pretty close to finished. At next meeting we can discuss which languages we want to use. From there we can finish up the last two questions.

**Comment by tanner-g** [comment]
Note: See Google Doc for group questions.

**Comment by JasonPuglisi** [comment]
Cool, I moved them to a new page for better tracking: https://github.com/JasonPuglisi/emmental/wiki/Development-FAQ%3A-Initial-design-and-tests
