### ISSUE TITLE
Create MySQL database

### ISSUE THREAD

**Issue by JasonPuglisi** [JasonPuglisi/emmental#22]
### Acceptance Criteria

1. Database must be an instance of MariaDB (a better version of MySQL) in Docker.
1. Database must be deployed via Docker Compose.
1. Database must follow the documented database schema.
1. If changes need to be made to the database schema, the documentation must be updated accordingly.

**Comment by tanner-g** [comment]
Status update: DB is created, works in Docker environment. Writing two tests for insertion and deletion of the DB. Once pushed and validated, this issue should be complete.
