### ISSUE TITLE
Create application server

### ISSUE THREAD

**Issue by JasonPuglisi** [JasonPuglisi/emmental#23]
### Acceptance Criteria

1. Application server must run Python.
1. Application server must be able to connect to the database.
1. Application server must be accessible by NGINX.
1. Application server must not be exposed to the external network.

Additional:

1. Functions must exist to create users, log users in, and log users out.
1. User creation must insert a user ID (GUID), username, and hashed password into the database.
1. User creation must automatically log the user in.
1. User login must insert a session ID (GUID) into the database and send that ID to the client.
1. User logout must remove the session ID from the database.

**Comment by tanner-g** [comment]
This is done when unit tests are written. 

Key unit tests include:
- adding users
- username and password checks
- site logon
- page navigation
- site restriction
