### ISSUE TITLE
Create authentication middleware

### ISSUE THREAD

**Issue by JasonPuglisi** [JasonPuglisi/emmental#26]
### Acceptance Criteria

1. Middleware must ensure unauthenticated users cannot access ANY page unless the page is whitelisted to be publicly accessible (deny by default).
1. The only whitelisted page must be the home (account creation/login) page.

### Notes

We must decide if we want to put the video files behind authentication. Serving them statically from NGINX would bypass our authentication, so it may be necessary to serve them via Python after all.

**Comment by tanner-g** [comment]
I think doing it python will be the easiest. I can set a "rule" at the top of every request and Ill make it such that you have to be an authenticated user to request the resource. its in my current implementation.
