### ISSUE TITLE
Create video platform development FAQ wiki page

### ISSUE THREAD

**Issue by JasonPuglisi** [JasonPuglisi/emmental#44]
### Acceptance Criteria

1. The attached documentation questions are answered in a new wiki page titled `Development FAQ: Video Platform`
1. The new wiki page is added to the wiki index on the home page of the wiki

### Questions

1. How do you prevent XSS is this step when displaying the username of the user who uploaded the video?
1. How do you ensure that users can’t delete videos that aren’t their own?

**Comment by tanner-g** [comment]
Working Responses:
- all our usernames are alpha numeric (we have username policies), there is also a set username length
- we use python libraries to handle string manipulation
- all flask variables are escaped out to HTML before being rendered to the page

**Comment by tanner-g** [comment]
To prevent users from deleting videos that are not their own, the deletion route will ensure that the video ID matches the user ID that is making the request.

**Comment by JasonPuglisi** [comment]
Done
