### ISSUE TITLE
Create SQL injection development FAQ wiki page

### ISSUE THREAD

**Issue by JasonPuglisi** [JasonPuglisi/emmental#56]
### Acceptance Criteria

1. The attached documentation questions are answered in a new wiki page titled `Development FAQ: SQL injection`
1. The new wiki page is added to the wiki index on the home page of the wiki

### Questions

1. How would you fix your code so that these issues were no longer present?
1. What are the limitations, if any that, of the SQL injection issues you've included?

**Comment by tanner-g** [comment]
Notes:
1. I would fix our code, by disallowing users from making direct sql queries on the db. Before introducing this vulnerability, we had prepared sql statements that prevented users from querying the db directly. Prepared statements help prevent the user from escaping strings or attempting to modify the sql query being made. There are also a few Python query conventions that we can follow that also help in handling variables used in sql queries. We rewrote them such that they didn't prevent the user from making those types of sql queries.

2. From our testing, a current limitation is the ability to modify the entries in the emmental db. We didn't include the python db save function, meaning that users can't modify the db from the queries they may make in the field provided.

**Comment by tanner-g** [comment]
WIP. updated text on wiki page

**Comment by tanner-g** [comment]
Just needs a quick review.

**Comment by JasonPuglisi** [comment]
> There are also a few Python query ing conventions that we can follow that also help in preventing SQL injection. We rewrote them such that they didn't prevent the user from making those types of SQL queries.

What does this mean? Seems sort of vague.

> We didn't include the python db that would allow users to make permanent changes.

This too. Another DB?

**Comment by tanner-g** [comment]
Reworded the two questions. Thanks for the feedback! Let me know what you think.
