### ISSUE TITLE
Create use cases

### ISSUE THREAD

**Issue by JasonPuglisi** [JasonPuglisi/emmental#6]
### Acceptance Criteria

1. Use cases are created according to the Unified Modeling Language (UML) (see link in resources)
1. Use cases are stored in the directory `/docs/use-cases/`
1. Use cases are well-defined for each application component

### Resources:

* Use case diagram guide: https://www.uml-diagrams.org/use-case-diagrams.html

**Comment by nixs123** [comment]
login, logout
upload video
ask chaim about other use cases we may need in app
