### ISSUE TITLE
Create database schemas

### ISSUE THREAD

**Issue by JasonPuglisi** [JasonPuglisi/emmental#9]
### Acceptance Criteria

1. Database schemas are created according to the Unified Modeling Language (UML) (see link in resources)
1. Database schemas are stored in the directory `/docs/database-schemas/`
1. Database schemas are well-defined and include each application component

### Resources:

* Database schema (entity relationship diagram) guide: https://www.visual-paradigm.com/VPGallery/datamodeling/EntityRelationshipDiagram.html

**Comment by tanner-g** [comment]
- db for auth
- db for content

**Comment by tanner-g** [comment]
- Need to add a PK logo to userID and add in a line between userID in content and users table
